### ISSUE TITLE
Does not take into account all time formats

### ISSUE THREAD

**Issue by micktaiwan** [jcontini/google-keep-scraper#2]
Keep/2018-12-06T21_15_37.264+01_00.html
Traceback (most recent call last):
  File "/home/mick/projects/google-keep-scraper/keep.py", line 22, in <module>
    xlDate = datetime.strftime(parse(googDate), '%m/%d/%Y %H:%M')
  File "/home/mick/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/home/mick/.local/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 649, in parse
    raise ValueError("Unknown string format:", timestr)
ValueError: (u'Unknown string format:', u'6 dic. 2018 21:15:37')

**Comment by jcontini** [comment]
Hi @micktaiwan ! Thanks for raising. Can you try again now that it's optimized for Python3?

**Comment by lchaumien** [comment]
Hello. 
I have the same parsing problem and i run it on Python 3.7.
Is it supposed to word with any date format ?

Thanks for your work anyway !
